### ISSUE TITLE
'RET' in a text field finishes and closes the survey

### ISSUE THREAD

**Issue by Mikolaj** [haskellweekly/haskellweekly#104]
I tried to enter more than one 'Other' answer to 'Which programming languages other than Haskell are you fluent in?', so I pressed RET in the text field thinking it would somehow got accepted and the field would clear for a new addition, but instead the survery finished and (I think), I can't go back and continue filling it.

Firefox, Ubuntu.

**Comment by tfausak** [comment]
This is the expected behavior. Solving it would require either changing the input text boxes to be `<textarea>`s or adding some JavaScript to prevent the default behavior.

**Comment by Mikolaj** [comment]
For me, the fact that pressing RET in an early texbox closes the whole survey was clearly unexpected. Otherwise, I would not do that and I would have the chance to actually fill the survey, not just an initial portion of it.

**Comment by tfausak** [comment]
Since the survey is now closed, I'm going to close this issue. However I've noted it in #100 and will be sure to address this next year. Thanks for providing your feedback!
