### ISSUE TITLE
Featuring a blog post on convolutional neural networks in Haskell

### ISSUE THREAD

**Issue by masterdezign** [haskellweekly/haskellweekly#11]
Hi! Here is a suggestion for your next issue:

[Convolutional Neural Networks Tutorial](http://penkovsky.com/neural-networks/day5/) by Bogdan Penkovsky
> Convolutional neural network is one of the most important deep learning
> architectures, it was even called the "master algorithm" in computer vision.
> To gain better understanding of the algorithm, today we are going to
> implement convolutional neural networks in Haskell on top of *massiv*,
> multi-dimensional arrays library.

**Comment by tfausak** [comment]
Looks great, thanks for the heads up!
