### ISSUE TITLE
How are articles curated?

### ISSUE THREAD

**Issue by phlummox** [haskellweekly/haskellweekly#118]
Hi,

I'd be interested to know how "featured articles" are curated in Haskell Weekly - perhaps that's something you could mention in the README for the repo?

Normally, I read at most a couple of blogs/articles mentioned in Haskell Weekly, but they have always seemed to be useful and interesting. So thank you! And mea culpa for not having provided positive feedback before.

This week, I encountered one that was in poor English, poorly written (incorrect use of terminology), and failed to give credit to previous writing in the area (it stated that "no-one has addressed" the issue being written about, which is patently untrue). I therefore wondered how it crept into the list.

I'm sure there's room for difference of opinion on whether an article/blog post is "good" or not, but this one surprised me, and I was then further surprised when I couldn't find any information on how articles get selected.

Cheers!

**Comment by tfausak** [comment]
It's entirely up to my discretion.

**Comment by phlummox** [comment]
No worries :) Just curious.
