### ISSUE TITLE
The State of PureScript Survey 2022 - The Results are In!

### ISSUE THREAD

**Issue by mikesol** [haskellweekly/haskellweekly#120]
If possible, we would love to publish a link to this in the upcoming edition of Haskell weekly.

https://discourse.purescript.org/t/the-state-of-purescript-survey-2022-the-results-are-in/2966

Thanks in advance for your consideration!

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll be sure to include a link to the PureScript survey results in tomorrow's issue.
