### ISSUE TITLE
New package: cabal-hoogle

### ISSUE THREAD

**Issue by kokobd** [haskellweekly/haskellweekly#129]
Hey, I wrote a tool to generate hoogle database for local packages and dependencies in cabal project: https://github.com/kokobd/cabal-hoogle
I've published it on Hackage: https://hackage.haskell.org/package/cabal-hoogle

Hope this will be added to the next newsletter. I can create a PR if this is eligible, but I'm not sure which section this should belong.

**Comment by tfausak** [comment]
I'd be happy to accept a PR for this! Typically I would put something like this in the "Show & tell" section.
