### ISSUE TITLE
Type-Signature

### ISSUE THREAD

**Issue by andys8** [haskellweekly/haskellweekly#131]
I want to share a functional programming game I developed because I wanted it to exist and to play myself. It's basically "Who Wants to Be a Millionaire?" - but with types. The game itself is implemented in PureScript and Open Source. Hope you'll consider it for the Haskell Weekly newsletter.

https://type-signature.com

**Comment by tfausak** [comment]
Look cool! I'd accept a PR to add this to the "Show & tell" section.

**Comment by andys8** [comment]
Awesome

**Comment by tfausak** [comment]
Fixed by #132.
