### ISSUE TITLE
Markov chain Monte Carlo (MCMC) sampling with Haskell

### ISSUE THREAD

**Issue by dschrempf** [haskellweekly/haskellweekly#133]
Hello!

I am developing Markov chain Monte Carlo library [mcmc](https://hackage.haskell.org/package/mcmc). The library has been in heavy use in our research projects for the last years, so I am confident it is doing its job well. Today I finished a brief [blog post](https://dschrempf.github.io/coding/2022-06-28-sample-from-a-posterior-using-markov-chain-monte-carlo-algorithms-and-haskell/) about a toy analysis of airline fatalities using the library. I am not sure if this is of interest to the readers of Haskell Weekly. If so, I'd be happy to contribute a link in one of the next issues!

I am looking forward to your comments!
Dominik

**Comment by tfausak** [comment]
Sounds interesting to me! I'd be happy to accept a PR.

**Comment by tfausak** [comment]
Closed by 83ae3871376eb950abfb02dde5f567524cdc3c47. Should be in issue 328. Thanks!

**Comment by tfausak** [comment]
No problem at all! Feel free to submit a PR whenever you write a blog post :)
