### ISSUE TITLE
cabal submission to Call for participation: add DeepSubsumption support

### ISSUE THREAD

**Issue by ulysses4ever** [haskellweekly/haskellweekly#134]
Hello! Cabal team would like to submit an entry to an upcoming HaskellWeekly issue, the Call to participation section:

- [cabal: Support extension DeepSubsumption from GHC 9.2.4](https://github.com/haskell/cabal/issues/8341)

**Comment by tfausak** [comment]
Great! Would you like to submit a PR for this?

**Comment by ulysses4ever** [comment]
Sure: #135.
