### ISSUE TITLE
Ema 0.8 announcement

### ISSUE THREAD

**Issue by srid** [haskellweekly/haskellweekly#137]
I just published a new post: https://srid.ca/ema-0.8

> **tldr**: Announcing a rewrite of [Ema](https://srid.ca/ema) (a static site generator in Haskell with hot reload destined to develop an unique kind of apps) with support for generic route encoders and composability.

I wanted to create a PR instead of opening this issue, but it looks like the new issue 330 has not been initialized yet?

**Comment by tfausak** [comment]
It is now! 😄 https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/issue-330.markdown
