### ISSUE TITLE
Cabal XDG testing

### ISSUE THREAD

**Issue by athas** [haskellweekly/haskellweekly#143]
I made [a post on the Haskell discourse](https://discourse.haskell.org/t/request-for-testing-of-the-xdg-enabled-cabal-install/5200/5) ([and my own blog](https://sigkill.dk/blog/2022-10-02-cabal-xdg.html)) about the new XDG support in cabal-install.  It would be nice to get a mention in the newsletter for more reach.

**Comment by tfausak** [comment]
Fixed by 26960a77af4da3a071acbef76f7ee90793ce90ee.
