### ISSUE TITLE
a tinny announcement to the issue 344

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#152]
Hi Taylor!
It would be great if you could add this post to the next Haskell Weekly: https://discourse.haskell.org/t/call-for-haskell-org-committee-nominations-the-2023-2025-term/5372

Thanks in advance. Till the next time!

**Comment by tfausak** [comment]
Of course! I'd be happy to include that announcement in the upcoming issue. 

For future reference, you could submit a PR adding this to the issue.
