### ISSUE TITLE
Build your own Redis in Haskell

### ISSUE THREAD

**Issue by sarupbanskota** [haskellweekly/haskellweekly#154]
Hey Taylor! Might be interesting for an upcoming edition — lmk if I should PR!

---

CodeCrafters supports [Haskell on its Redis challenge](https://app.codecrafters.io/tracks/haskell). An interesting way to dive deeper into Redis internals, while strengthening your Haskell muscle.

**Comment by tfausak** [comment]
Looks cool! I'll be sure to include it in the upcoming issue. I'd be happy to accept PRs for stuff like this in the future 😄
