### ISSUE TITLE
content suggestion - The 7 GUIs in Haskell post series

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#158]
The 7GUIs in Haskell using the reflex framework:

1. Part one (the counter): https://blog.obsidian.systems/seven-guis-in-reflex-vty-part-1-the-counter/
2. Part two (the temperature converter) https://blog.obsidian.systems/seven-guis-in-reflex-vty-part-2-the-temperature-converter/

**Comment by tfausak** [comment]
Looks great! Thanks for the suggestion. I'll be sure to include it in the upcoming issue. 

In the future, feel free to submit a PR for suggestions like this. I welcome all contributions!
