### ISSUE TITLE
Add "The hakyll-nix-template Tutorial" post

### ISSUE THREAD

**Issue by rpearce** [haskellweekly/haskellweekly#165]
Hi! It's been a while since I contributed a link, and I don't see a new template ready for the next issue, so I'm sharing here if you think it's worthy.

[The hakyll-nix-template Tutorial](https://robertwpearce.com/the-hakyll-nix-template-tutorial.html)

> A full walkthrough for getting set up to create static sites using nix and hakyll.

Thanks for maintaining this!

**Comment by tfausak** [comment]
Definitely worthy! If you'd like to submit a PR, the new issue has been scaffolded: https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/issue-355.markdown

**Comment by rpearce** [comment]
Done! 👆
