### ISSUE TITLE
Broadcasting a Haskell Playground ticket: Listing the packages exposed and their versions

### ISSUE THREAD

**Issue by Kleidukos** [haskellweekly/haskellweekly#166]
Hi @tfausak!

We'd be immensely grateful if you could include this ticket in the next issue of the newsletter: https://github.com/tomsmeding/play-haskell/issues/17 :heart:

**Comment by tfausak** [comment]
Of course! If you'd like to submit a PR, the new issue has been scaffolded: https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/issue-355.markdown
