### ISSUE TITLE
Add "A concise introduction to `generics-sop`" article

### ISSUE THREAD

**Issue by srid** [haskellweekly/haskellweekly#167]
https://srid.ca/generics-sop-intro

I'm happy to open the PR myself after the `.md` for next newsletter gets added to the repo.

**Comment by tfausak** [comment]
Sorry for the delay! The new issue has been scaffolded: https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/issue-355.markdown
