### ISSUE TITLE
Content suggestion: series about platonic Hask

### ISSUE THREAD

**Issue by viviag** [haskellweekly/haskellweekly#172]
I publish it [here](https://viviag.io/tagged/hask/) and hope it is worthy and publication will trigger me to invest more time to the series. Hopefully one or two new texts will appear before Friday.

**Comment by tfausak** [comment]
Sure, I'd happily accept a PR adding your latest post to the upcoming issue. Also if you're interested in feedback, I'd recommend posting to the [Discourse](https://discourse.haskell.org) or [sub-Reddit](https://www.reddit.com/r/haskell/).

**Comment by viviag** [comment]
Looks like I will complete the next post tomorrow. Is it still better to publish current latest?
