### ISSUE TITLE
Content suggestion: CfP for 36th Aga Implementors' Meeting 

### ISSUE THREAD

**Issue by liesnikov** [haskellweekly/haskellweekly#184]
I'm co-organising 36th AIM and wanted to announce it on Haskell Weekly. [Last time](https://haskellweekly.news/issue/229.html) the advert was not too long, so we can keep format the same:

[Agda Implementors' Meeting XXXVI](https://wiki.portal.chalmers.se/agda/Main/AIMXXXVI)
The thirty-sixth Agda Implementors' Meeting will take place in Delft, NL from Wednesday, 2023-05-10 to Tuesday, 2023-05-16.
The meeting aims to bring together people not only developing but also using Agda. We will have talks on the implementation details of Agda in the morning and code sprints in the afternoon.
There's a (soft) deadline for registration on 2023-04-12.

**Comment by tfausak** [comment]
Thanks for the suggestion! I added this in c7ac3d2aef9a55626832f08799cbc3f566e4ac17.
