### ISSUE TITLE
Haskell support in Fleet/Zed

### ISSUE THREAD

**Issue by unorsk** [haskellweekly/haskellweekly#186]
This isn't exactly news. But I though it could be nice including these two links in upcoming issues.
The community would benefit from more IDEs supporting Haskell. And it seems that the number of voices required for that isn't especially large.

[Vote for Haskell support in Fleet](https://youtrack.jetbrains.com/issue/FL-15723/Haskell-Support)
[Vote for Haskell support in Zed](https://github.com/zed-industries/community/issues/343)

**Comment by tfausak** [comment]
I'm sorry, I don't think these would be a good fit for Haskell Weekly.

**Comment by unorsk** [comment]
That's ok, np!
