### ISSUE TITLE
Empty link in the HW email

### ISSUE THREAD

**Issue by hsyl20** [haskellweekly/haskellweekly#19]
In the HTML version of the HW email, the title "Haskell Weekly" has a link without target. Could you fix this? I'm tired of clicking on it every single week. ;)

Thanks for your work!

PS: initally I sent this to info@haskellweekly.news but it failed after five days with:
```
This is the mail system at host mo529.mail-out.ovh.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<info@haskellweekly.news>: connect to mx5.name.com[173.192.7.100]:25:
    Connection timed out
```

**Comment by tfausak** [comment]
Huh, weird. On both counts. 

The link in the title should be pulled from the RSS/Atom feed, which I think is set up correctly. Maybe there’s another tag I need to add or something. 

I sent myself a test email (to `info@haskellweekly.news`) this morning and it worked quickly. 

Unfortunately both problems are a little bit out of my hands. MailChimp handles generating the emails and Name.com handles receiving emails. I haven’t changed anything about either system in a while.

**Comment by hsyl20** [comment]
> The link in the title should be pulled from the RSS/Atom feed, which I think is set up correctly. Maybe there’s another tag I need to add or something.

It is set up correctly in the plain text email, but not in the HTML email.
The newsletter archive also has the issue (e.g. https://us10.campaign-archive.com/?e=da7b728ce2&u=49a6a2e17b12be2c5c4dcb232&id=6a615c6f19).

> I sent myself a test email (to info@haskellweekly.news) this morning and it worked quickly.

I will retry. maybe it was temporary.
