### ISSUE TITLE
PureScript survey results and Haskell->JS podcast

### ISSUE THREAD

**Issue by mikesol** [haskellweekly/haskellweekly#191]
Hi!

I'm on the PureScript core team and we recently concluded our 2023 survey. We're looking for a happy home to publish the results, and as the most common path to our community is from Haskell (the survey results have indicated this for two years straight), we thought that Haskell Weekly could be a good place to post the survey write-up. Please let me know if this would be ok.

In parallel, we thought it would be interesting to have an episode of the HW podcast dedicated to Haskell-to-JS and Haskell-to-WASM technologies. In addition to GHC's JS and WASM support, several languages written in Haskell have JS backends (Elm, PureScript), and some languages inspired by Haskell (ie Idris) also have a JS backend. Many questions loom large about feature sets, consolidation, industry trends, etc, so I think a podcast with reps from several of these projects could be quite interesting, and it'd give us a chance to bring up some observations from our survey results that could be relevant to many of these projects.

Please let me know what you think of these two ideas and thanks for your consideration!

**Comment by tfausak** [comment]
Sure, I'd be happy to include the PureScript survey results in the Haskell Weekly newsletter. 

Unfortunately I doubt I'll be making any more episodes of the podcast. Perhaps you could talk to the folks at the Haskell Interlude? https://haskell.foundation/podcast/

**Comment by tfausak** [comment]
Sorry, I think perhaps there's been a miscommunication. The Haskell Weekly newsletter doesn't post content itself, rather it links to content. I could link to your comment here, but that would be a bit strange. Are you going to post these results anywhere else, such as the PureScript Discourse?

**Comment by mikesol** [comment]
Ah apologies, I missed that.

We posted the survey results on our Discourse last year, but it didn't get as widely seen as we would have hoped, so we're looking to partner with an organization that has more reach in the functional programming community.

I can for sure send you the link once we post it.

If it's not too much to ask, would you have any suggestions for publications to approach that would be a happy home for our survey results?

**Comment by tfausak** [comment]
In my opinion, posting to Discourse is fine. People also sometimes post things to a Gist on GitHub. Or if anyone involved with the survey has a personal blog they want to host the results on, that works too.

**Comment by mikesol** [comment]
Done! https://discourse.purescript.org/t/the-state-of-purescript-survey-2023-the-results-are-in/3523. If you're still open to posting this on Haskell Weekly, we'd be much obliged! Thanks for the suggestions :)

**Comment by tfausak** [comment]
Fixed by #199.
