### ISSUE TITLE
Blog post for fancy Haskell

### ISSUE THREAD

**Issue by dfithian** [haskellweekly/haskellweekly#21]
I wrote a blog post following up on some others about writing "fancy" Haskell.

Here are some of the inspirational posts:
* https://www.parsonsmatt.org/2019/12/26/write_junior_code.html
* https://cvlad.info/junior-developers/

And here is mine:
https://dfithian.github.io/2019/12/30/fancy-haskell.html

Thank you!

**Comment by alexeyzab** [comment]
Will add to this week's issue, thanks!
