### ISSUE TITLE
Content suggestion: XML stream processing with Haskell

### ISSUE THREAD

**Issue by marhop** [haskellweekly/haskellweekly#229]
Hi,

I wrote a blog post about XML stream processing with the xml-conduit package. Maybe that's interesting for some people.

https://martin.hoppenheit.info/blog/2023/xml-stream-processing-with-haskell/

Cheers,
Martin

**Comment by alexeyzab** [comment]
Nice, will add!

**Comment by alexeyzab** [comment]
Added in [032fd44](https://github.com/haskellweekly/haskellweekly/pull/228/commits/032fd4459f7d65538d98241fe273bae86e76e154), thanks!
