### ISSUE TITLE
Nominees for packages of the week section

### ISSUE THREAD

**Issue by lehins** [haskellweekly/haskellweekly#23]
Here are two cool packages that I've developed over time that I'd like to nominate be added to packages of the week section:

* [`Color`](https://github.com/lehins/Color) - was announced on [Reddit yesterday](https://www.reddit.com/r/haskell/)
* [`safe-decimal`](https://github.com/fpco/safe-decimal) - has a blog post upcoming from FP Complete likely next week.

**Comment by tfausak** [comment]
I've linked both the `Color` announcement and the `safe-decimal` blog post in issue 198. Thanks!
