### ISSUE TITLE
Content suggestion: Blog post on Haskell LSP integration

### ISSUE THREAD

**Issue by madgen** [haskellweekly/haskellweekly#243]
Hi, I wrote a blog post about LSP integration using the `lsp` library and a corresponding extension in VSCode:

https://dodisturb.me/posts/2023-09-30-Haskell-LSP-Laboratory.html

Can it be added to featured content please?

Thank you

**Comment by alexeyzab** [comment]
Hi! Will add it to this week's issue, thanks! This fits pretty well into our `Show and Tell` section, IMO, would you be fine with that?

**Comment by madgen** [comment]
Sure, that'd be great.

**Comment by alexeyzab** [comment]
Added in [ef7780a](https://github.com/haskellweekly/haskellweekly/pull/242/commits/ef7780a0216e4a7951e170d1319d12d3f9e8251a#diff-3b72f7e4c0abdf911b95f4c0207c295d799c63a8218162e68431b2d91315cc32R60) 🎉
