### ISSUE TITLE
Add rhine-bayes blog post

### ISSUE THREAD

**Issue by turion** [haskellweekly/haskellweekly#246]
I wrote a blog post about [`rhine-bayes`](https://hackage.haskell.org/package/rhine-bayes): https://www.tweag.io/blog/2023-10-12-rhine-bayes/, this would be a good item for the next newsletter.

**Comment by alexeyzab** [comment]
Will add, thank you!

**Comment by alexeyzab** [comment]
Added in [6f5aa4f](https://github.com/haskellweekly/haskellweekly/commit/6f5aa4f9ecadd9e79ab178e3419c4be5dae31b0a)
