### ISSUE TITLE
FP Dag 2024 in Delft

### ISSUE THREAD

**Issue by jespercockx** [haskellweekly/haskellweekly#250]
The Netherlands Functional Programming Day (or FP Dag) is an annual gathering of researchers, students, and practitioners sharing a common interest in functional programming. The day features talks that cover the latest advances in research, teaching and applications in the area of functional programming and (implementation of) functional languages. 

The FP Dag will take place on January 5th 2024, at the Technical University of Delft. 

Participation is free of charge, but registration is required:

	https://www.aanmelder.nl/fp-nl2024/subscribe

There is a soft registration deadline of **Friday 22 December 2023**.

Colleagues from neighboring countries are more than welcome to attend; the language of the FP Day is English.

More information can be found on the website:

	https://www.tudelft.nl/fpday-2024

**Comment by alexeyzab** [comment]
Thanks, I will add it to the upcoming issue.

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/251/commits/f33a919832aabb39b4713ed6f9b55c5ad6093766#diff-e48ed0e05cf58c5992c4a9dd38d99e1309898285207c3935d48327e53e25e6d6R25
