### ISSUE TITLE
Haskell Refactor Step Through - Alternative Solutions

### ISSUE THREAD

**Issue by SaachiKaup** [haskellweekly/haskellweekly#252]
Hello!

I am the teaching assistant of a study group that teaches Haskell. In a previous newsletter issue, a [Freckle Blog](https://tech.freckle.com/2023/10/31/haskell-refactoring-step-through/) posed an interesting problem. 

I have written an article which provides alternative solutions to the problem: [Haskell Refactoring 2.0](https://medium.com/@saachi.kaup146/haskell-refactor-2-0-66bc7990e256).

Do let me know if this can be published. 

Thanks and Regards,
Saachi K

**Comment by alexeyzab** [comment]
Hi! Will add it to this week's issue, thanks!

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/251/commits/f33a919832aabb39b4713ed6f9b55c5ad6093766#diff-e48ed0e05cf58c5992c4a9dd38d99e1309898285207c3935d48327e53e25e6d6R20
