### ISSUE TITLE
The Scale By The Bay 2023 videos are out!

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#264]
it is worth spreading around that:

Tikhon Jelvis' Better Code Design with Types and Concepts https://www.youtube.com/watch?v=Pp43qHiWtFk
Avi Press' Why Haskell is a Terrible Choice for Startups (And Why We Picked It Anyway) https://www.youtube.com/watch?v=qw4S_6FXsp4
Ivan Perez's, Open Source in Space https://www.youtube.com/watch?v=V0qD4ychpuI

recordings are out!

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/263/commits/2f5649c18c24282c71279a9413e8ca3af5a82c25
