### ISSUE TITLE
Documentation help wanted: Educate users on making flag-dependent APIs in cabal files

### ISSUE THREAD

**Issue by Kleidukos** [haskellweekly/haskellweekly#274]
Hello! I would like to broadcast a call for documentation help in the cabal manual.

> We want to educate our users regarding APIs exposed (or not) depending on a cabal flag.
> The user manual should reflect that this is a bad idea.
> See https://github.com/haskell/cabal/issues/8128.
> Thank you!

**Comment by alexeyzab** [comment]
Will add it to the next issue, thank you!

**Comment by alexeyzab** [comment]
Added in [c52173b](https://github.com/haskellweekly/haskellweekly/pull/275/commits/c52173bf89906fd99ae055dbb3bff563f5889545#diff-653e4bf1fd3d94383579c827ba5240fdfdf25477d2f7c75e84cb3d2008eed148R60)!
