### ISSUE TITLE
Subdirectories for newsletter directory?

### ISSUE THREAD

**Issue by ulysses4ever** [haskellweekly/haskellweekly#278]
It's a little annoying how big `data/newsletter` grew. It'd be nice to split it into subdirs, I think. E.g. we could have subdirs for hundreds

```
data/newsletter
├── 100
│  ├── issue-100.markdown
│  ├── ...
├── 200
│  ├── issue-200.markdown
│  ├── ...
...
```

**Comment by tfausak** [comment]
Sure, that's reasonable. It could also go by year.

**Comment by ad-si** [comment]
I think year would be more helpful.

**Comment by ulysses4ever** [comment]
For me, the issue number would be more convenient because most of the time I search by the number and have no idea what year some issue appeared in. Also load balancing is perfect :-) But if people think year is better, I'm fine with that too. Any way helps my main case: finding the latest issue faster. Also, year sounds to me mathinaly better but harder to do, so cost/benefit isn't great. Why do you like year more anyway?
