### ISSUE TITLE
Tool for git project management

### ISSUE THREAD

**Issue by dfithian** [haskellweekly/haskellweekly#28]
Hi, I was wondering if you would add this to next week's issue! It's kind of small in terms of code, but hey that's the main draw of Haskell 😛 .
https://dfithian.github.io/2020/03/09/git-project-management.html

**Comment by tfausak** [comment]
Sure thing! Thanks for the suggestion.

**Comment by tfausak** [comment]
Fixed by a83885395f1546d935373ef018f70b4d61eb545d.

**Comment by dfithian** [comment]
Thanks so much!
