### ISSUE TITLE
Blog post: "Managing change with Rollout Flags" on the Scrive Engineering blog

### ISSUE THREAD

**Issue by theophile-scrive** [haskellweekly/haskellweekly#289]
Hi! This article was published on the Scrive Engineering blog, with implementation of the concept in Haskell, as we use it on the backend: https://tech.scrive.com/2024-03-19-managing-change-with-rollout-flags/

**Comment by alexeyzab** [comment]
Nice, will add it to this week's issue. Thanks!

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/288/commits/6ae58c0845f4e4493e8fb544b829734cb9d91a9c!
