### ISSUE TITLE
Lambda Conference 2024

### ISSUE THREAD

**Issue by avanmeul** [haskellweekly/haskellweekly#291]
Lambda Conference (LambdaConf) 2024 [ https://www.lambdaconf.us/ ] will be in early May this year, in Estes Park, Colorado.

Haskell Weekly readers would likely want to know about this important conference.  This will be the first LambdaConf after the pandemic.

**Comment by avanmeul** [comment]
I wrote some of the staff of Lambda Conference to tell them about my mention of Lambda Conference so that they could react and/or comment.  They suggest the following for a Haskell Weekly announcement (rather than my terse summary).  I quite agree:  their announcement is more apropos and informative for your audience.

* * *
LambdaConf 2024 ([lambdaconf.us](http://lambdaconf.us/)) will be held in Estes Park, CO., from May 4 - 10. Speakers from across a range of disciplines, with a special emphasis on functional programming, will share their knowledge throughout two days of talks. Attendees will also have the opportunity to participate in pre-conference activities, a hackathon, and a professional development workshop on Rust.

The readers of Haskell Weekly are welcomed to join the first in-person LambdaConf since 2019!

**Comment by alexeyzab** [comment]
Hi there André! We don't have a section dedicated to events, but I can add this to our `Call For Participation` section, hope that works.

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/292/commits/69b9739272b5f1e1fd00d9643509385dea38acc4, thank you!

**Comment by avanmeul** [comment]
Thank you!
