### ISSUE TITLE
PenroseKiteDart

### ISSUE THREAD

**Issue by tfausak** [haskellweekly/haskellweekly#296]
https://readerunner.wordpress.com/2024/04/08/penrosekitedart-user-guides/

**Comment by chrisreade** [comment]
There is also a small art gallery for PenroseKiteDart
[here](https://github.com/chrisreade/PenroseKiteDart/tree/master/SVGs/ArtGallery)

**Comment by alexeyzab** [comment]
Added in [5727972](https://github.com/haskellweekly/haskellweekly/pull/294/commits/57279720fb8a5c99fceae1038cd98c1bf87fc60f)
