### ISSUE TITLE
featuring article on Why Haskell Matters

### ISSUE THREAD

**Issue by thma** [haskellweekly/haskellweekly#31]
Hi! I want to suggest this article for the next issue:

[Why Haskell Matters](https://github.com/thma/WhyHaskellMatters/blob/master/README.md) by @thma

In this article I try to explain why Haskell keeps being such an important language by presenting some of its most important and distinguishing features and detailing them with working code examples.

The presentation aims to be self-contained and does not require any previous knowledge of the language.

The target audience are developers with a background in non-functional languages who are eager
to learn about concepts of functional programming and Haskell in particular.

**Comment by tfausak** [comment]
Looks great! I'll be sure to include it in tomorrow's issue. Thanks!

**Comment by thma** [comment]
thanks !

**Comment by tfausak** [comment]
Fixed by 0d752a8c2f3f88a1dca87959638231b87b4d9fc0.
