### ISSUE TITLE
[blogpost] 12 Reasons Why Haskell is a Terrible Choice for Startups (and why we picked it anyway)

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#313]
https://about.scarf.sh/post/12-reasons-why-haskell-is-a-terrible-choice-for-startups-and-why-we-picked-it-anyway

**Comment by alexeyzab** [comment]
Hi! I generally try to add posts that are more recent in each week's issue. However, if there aren't that many such posts this week, I'll include this too. Thanks!

**Comment by alexeyzab** [comment]
Added in [1e92e14](https://github.com/haskellweekly/haskellweekly/pull/315/commits/1e92e14b5c39e13bdd5aef3632871a651ec06102)
