### ISSUE TITLE
Add Portland Has Skill meetup announcement?

### ISSUE THREAD

**Issue by kaBeech** [haskellweekly/haskellweekly#316]
Hi!

I just announced a [Haskell meetup](https://www.meetup.com/portland-has-skill/) in Portland, Oregon and I'd like to get the word out as I don't know any local Haskellers.

Would it be appropriate to include a blurb in the Haskell Weekly Newsletter?

If so I'd be happy to submit a PR that adds it, though I'm not sure which section would be best to add it to.

If you have any other suggestions for ways to get the word out I would love to hear them as well!

Thank you for all your work! 💙

**Comment by alexeyzab** [comment]
Hi! We don't have a separate `Events` section but I've [included it in the CFP section](https://github.com/haskellweekly/haskellweekly/pull/322/files#diff-5e2be52bf50de8c196b997020caba9cbcba9015ae83fcdbd8c7a137a72718f68R51), thank you! 

As far as getting the word out goes, I'd probably do the same thing you did with posting it on reddit/including it here and so on. Maybe reaching out to other Haskell meetup organizers to pick their brains would be useful? The Bay Area Haskell meetup has a lot of members, though I believe the current organizers aren't the same people as the ones that started it.

The company I work at (Mercury) has an office in Portland, we have a handful of Haskell engineers located in that area, I just asked them in Slack if they would be interested in co-hosting this meetup at the office in the future. If they are up for it, I'll reach out to get you in touch with the folks there!

**Comment by kaBeech** [comment]
Ooh, that would be amazing - thank you so much @alexeyzab!
