### ISSUE TITLE
Parallel QuickCheck (QuickerCheck)

### ISSUE THREAD

**Issue by Rewbert** [haskellweekly/haskellweekly#317]
Hi!

I recently implemented a new, parallel, runtime for QuickCheck. I would love for more people to hear about this and, most importantly, perhaps try it out. It is a simple drop-in replacement of QuickCheck. While the plan is to eventually merge it, it will take a while.

Our evaluation showed that there are, unexpectedly so, a lot to gain in terms of performance when using more cores. We also implement and evaluate parallel shrinking, which also shows promise.

I wrote up some words about it here (https://www.krook.dev/posts/quickercheck/quickercheck.html), as well as instructions of how to get it up and running.

**Comment by alexeyzab** [comment]
Hi there! Added it in this [week's issue](https://github.com/haskellweekly/haskellweekly/pull/322/files#diff-5e2be52bf50de8c196b997020caba9cbcba9015ae83fcdbd8c7a137a72718f68R22), thank you!
