### ISSUE TITLE
Blog post: Building a data compression utility in Haskell using Huffman codes

### ISSUE THREAD

**Issue by lazamar** [haskellweekly/haskellweekly#327]
Hi,

I wrote a post on building a data compression utility in Haskell using Huffman codes and I think it might be a good addition to the weekly newsletter.

It explores Huffman codes, data serialisation, and using laziness to keep a low memory footprint without losing on modularity or simplicity.

https://lazamar.github.io/haskell-data-compression-with-huffman-codes/

**Comment by alexeyzab** [comment]
Will add to this week's issue, thank you!

**Comment by alexeyzab** [comment]
Added in https://github.com/haskellweekly/haskellweekly/pull/328/commits/1aa8f34d9e6df8df76e85c3886ed30a5ffa98b5d
