### ISSUE TITLE
Haskell on AWS Lambda - A Detailed Tutorial

### ISSUE THREAD

**Issue by saurabhnanda** [haskellweekly/haskellweekly#33]
Hi, I've written a long-form tutorial at [Haskell on AWS Lambda - A Detailed Tutorial](https://www.haskelltutorials.com/haskell-aws-lambda/). This is based on our experience, at [Vacation Labs](https://www.vacationlabs.com), of writing a Haskell component that runs on AWS Lambda.

It covers the following topics:

- [How to use `amazonka` to manage simple AWS Lambda functions](https://www.haskelltutorials.com/haskell-aws-lambda/managing-simple-lambda-functions-using-haskell.html)
- [Writing your own custom runtime for running Haskell code in AWS Lambda](https://www.haskelltutorials.com/haskell-aws-lambda/custom-aws-lambda-runtime-for-haskell.html)
- [Using Docker to compile your custom AWS Lambda runtime and **automatically packaging native library dependencies**](https://www.haskelltutorials.com/haskell-aws-lambda/compiling-haskell-runtime-in-docker.html)
- [Creating and managing AWS Lambda functions completely in Haskell](https://www.haskelltutorials.com/haskell-aws-lambda/managing-lambda-functions-completely-in-haskell.html)

**Comment by tfausak** [comment]
Looks great! Thanks for the suggestion. I'll be sure to include it in the upcoming issue.

**Comment by tfausak** [comment]
Added in 08e2f5fbc61641770fbe34ee7fea55799c36436b.

**Comment by saurabhnanda** [comment]
Thanks 😀
