### ISSUE TITLE
Silicon Valley Haskell Meetup

### ISSUE THREAD

**Issue by mpscholten** [haskellweekly/haskellweekly#331]
I'm organising a new Haskell Meetup in the SF Bay Area. So far we have 17 Haskeller's coming, and Avi Press (Founder @ Scarf and on the board of the Haskell Foundation) and Tim Sears (VP Systems & Application Engineering @ Groq) The first event is this friday 6pm at [Groq in Mountain View](https://wow.groq.com/)

Full details: https://docs.google.com/document/d/1Tjy9gkyikih6PqjhQ8F5-Imtafj-7xyg3O0des3fRFw/edit?usp=sharing

Any chance it can be included with the newsletter?

**Comment by alexeyzab** [comment]
We no longer maintain an events section but I'll include this in the CFP section, thanks!

**Comment by alexeyzab** [comment]
Added in [b1498df](https://github.com/haskellweekly/haskellweekly/pull/332/commits/b1498df5c2cc78514a41d56af9875a0a50cd12d1)

**Comment by mpscholten** [comment]
Thanks 👍
