### ISSUE TITLE
[blogpost] Building Scarf: Avi Press on Haskell, Telemetry, and Open Source Challenges

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#333]
https://about.scarf.sh/post/building-scarf-avi-press-on-haskell-telemetry-and-open-source-challenges

**Comment by alexeyzab** [comment]
Hi! The podcast described in the post was already included in [issue 416](https://github.com/haskellweekly/haskellweekly/blob/haskellweekly/data/newsletter/2024/issue-416.markdown). I realize that the post is mostly a summary of that episode from April so I am erring on the side of not including it this week. Thanks!
