### ISSUE TITLE
[blog] Why Does Everyone Hate Haskell, Jazz, and Pure Math?

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#337]
https://adueck.github.io/blog/on-haskell-jazz-and-pure-math/

**Comment by alexeyzab** [comment]
Hi! This article was posted on July 11th, and I generally try to include the more recent posts in each newsletter, specifically those within the last week or so.

**Comment by idabzo** [comment]
I understand your point, but I believe this is an evergreen piece that addresses a perspective that has been notably absent in the community. I posted it on LinkedIn three days ago in the Haskell Enthusiasts Group, and it received a strong positive response, which suggests that the community found it valuable.

Despite the timing, I think it’s still worth promoting because the content remains relevant and impactful. Interestingly, it also got posted on Hacker News with a delay (https://news.ycombinator.com/item?id=41160318), but it still resonated well there too.

**Comment by tfausak** [comment]
Alexey is the editor. It’s up to him. 

When I was the editor, I tried to limit entries to the past couple weeks. There’s an endless number of evergreen posts of various ages. The line must be drawn somewhere.
