### ISSUE TITLE
featuring article on Implementing Clean Architecture with Haskell and Polysemy

### ISSUE THREAD

**Issue by thma** [haskellweekly/haskellweekly#36]
Hi! I want to suggest this article for the next issue:

[Implementing Clean Architecture with Haskell and Polysemy](https://github.com/thma/PolysemyCleanArchitecture#readme) by  @thma (Thomas Mahler)

This article shows how algebraic effect systems can be used to maintain a clear separation of concerns between different parts of software systems. From a practical programming perspective this improves composability and testability of software components.

I'm demonstrating this idea by using the Polysemy library to implement a multi-layered REST application conforming to the guidelines of the Clean Architecture model.

**Comment by tfausak** [comment]
Thanks for the heads up! I will be sure to feature your article in the upcoming issue.

**Comment by tfausak** [comment]
Closed by 791fbde88534a9b7b0b2c195ef861c084f10c8c1.
