### ISSUE TITLE
[blogpost]A Dictionary of Single-Letter Variable Names

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#367]
http://jackkelly.name/blog/archives/2024/10/12/a_dictionary_of_single-letter_variable_names/

**Comment by alexeyzab** [comment]
Added in [e529ccf](https://github.com/haskellweekly/haskellweekly/pull/368/commits/e529ccf5845397b89b542c86ee9f5afcb19f6391), thanks!
