### ISSUE TITLE
[Show and Tell] Pattern Matching and Records in Haskell Video

### ISSUE THREAD

**Issue by LigerLearn** [haskellweekly/haskellweekly#370]
For the next issue's show and tell section:

- [Pattern Matching and Records in Haskell](https://youtu.be/e4_3uZXvoak) by LigerLearn
  > An introduction for beginners into the concepts of pattern matching and records in Haskell. Pattern matching concepts covered include simple matching, (_) wildcard matching, matching tuples, matching custom types, matching lists, as patterns, guards, and case expressions. Part of the [Intro to Functional Programming with Haskell Course](https://www.youtube.com/playlist?list=PLMWwct3_kb-2xtOziG1gQYMVr691GadR4)

**Comment by alexeyzab** [comment]
Added in [5157595](https://github.com/haskellweekly/haskellweekly/pull/372/commits/51575955ebea7869b65a631ad60eed8e5be5f41d), thanks!
