### ISSUE TITLE
[MuniHac 2024 videos] The playlist

### ISSUE THREAD

**Issue by idabzo** [haskellweekly/haskellweekly#371]
https://www.youtube.com/playlist?list=PLxxF72uPfQVRWswMN2-KsSYW6fDdQY1wi

**Comment by alexeyzab** [comment]
Added in [5157595](https://github.com/haskellweekly/haskellweekly/pull/372/commits/51575955ebea7869b65a631ad60eed8e5be5f41d), thanks!
