### ISSUE TITLE
Clay is looking for contributions

### ISSUE THREAD

**Issue by turion** [haskellweekly/haskellweekly#39]
Hi, I'm the current maintainer of `clay`, a CSS preprocessor. Not being a CSS expert, not involved in frontend development and tied up with other projects, I only do maintainership and can't contribute new features. It seems there is noone else is actively bringing a lot of new features ahead, but there is still some interest in `clay`. Is it ok to link a `clay` issue in "Call for participation"? For example this one: https://github.com/sebastiaanvisser/clay/issues/176

**Comment by tfausak** [comment]
Sounds good! I'd be happy to include Clay in the CFP section. 

Pinging @alexeyzab since he normally puts that bit together.

**Comment by tfausak** [comment]
Fixed here: https://github.com/haskellweekly/haskellweekly/commit/edc92fea91890ffd56269d6f45c6e8fbdb472359#diff-96a2c3ad053ec34c2a6bc2e1808f6da3R99

**Comment by alexeyzab** [comment]
Oh snap, sorry I missed this!
