### ISSUE TITLE
featuring article on Getting Started with Haskell on Fedora

### ISSUE THREAD

**Issue by TristanCacqueray** [haskellweekly/haskellweekly#41]
Hi! I want to suggest this article for the next issue:

https://fedoramagazine.org/getting-started-with-haskell-on-fedora/ by @TristanCacqueray

In this article I show how to run ghc on Fedora and explain why you would want to do that.

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll be sure to feature this in the upcoming issue.

**Comment by TristanCacqueray** [comment]
Thank you very much for the mention!
