### ISSUE TITLE
Submission to Haskell Weekly

### ISSUE THREAD

**Issue by mikesol** [haskellweekly/haskellweekly#45]
Hi. A member of the [PureScript community](https://functionalprogramming.slack.com/archives/C04NA444H/p1599233340038100?thread_ts=1599205014.034800&cid=C04NA444H) suggested that I submit this article to Haskell Weekly: https://meeshkan.com/blog/purescript-2020/. Please let me know if you find it interesting/valuable and, if so, what the next steps would be. Thanks!

**Comment by tfausak** [comment]
Looks interesting! Thanks for the suggestion. I'll be sure to feature it in the upcoming issue.
