### ISSUE TITLE
Submission for next week on the launch of my new book

### ISSUE THREAD

**Issue by isovector** [haskellweekly/haskellweekly#46]
Hoping to get this in for next week! Thanks <3

From reddit: https://www.reddit.com/r/haskell/comments/iqf489/ann_my_new_book_algebradriven_design_is_now/?

> I am thrilled to announce my new book, Algebra-Driven Design. It's the culmination of two rewrites and a year of research, and comes with a foreword written by John Hughes, the inventor of QuickCheck.
> 
> In the book, we take a fundamentally different approach to the software design process, focusing on deriving libraries from equations, algebraic manipulation and well-studied mathematical objects. The resulting code is guaranteed to be free of abstraction leaks, and in many cases, actually writes itself.
> 
> If that sounds like the sort of software you'd like to write, I'd highly encourage you to give it a read.

**Comment by tfausak** [comment]
Thanks for the suggestion!
