### ISSUE TITLE
Agda Implementors' Meeting XXXIII

### ISSUE THREAD

**Issue by jespercockx** [haskellweekly/haskellweekly#47]
The  thirty-third Agda Implementors' Meeting will take place online from  Monday 2020-10-12 to Friday 2020-10-23. The meeting will be organized in  a similar way to AIM XXXII, with a reduced program spread over two  weeks. See the wiki for details: https://wiki.portal.chalmers.se/agda/Main/AIMXXXIII

Since Agda is both implemented in Haskell and shares a lot of common roots, I think this could also be very interesting to the Haskell community.

**Comment by tfausak** [comment]
Thanks for the suggestion!
