### ISSUE TITLE
News item: reanimate v1.0 release

### ISSUE THREAD

**Issue by Lemmih** [haskellweekly/haskellweekly#48]
Reanimate v1.0 was released today.
Haskell Cafe announcement: https://mail.haskell.org/pipermail/haskell-cafe/2020-September/132745.html
r/haskell: https://www.reddit.com/r/haskell/comments/iw8ku0/reanimate_v10/

Bread text:
> It is my great pleasure to announce version 1.0 of the Reanimate animation library. Reanimate aims to be a batteries-included way of creating animations and illustrations. To see it in action, visit:
> 
> https://reanimate.github.io/
> 
> Reanimate wouldn't be here without help and I'd like to thank Jan Hrček for writing the Elm viewer, Shaurya Gupta for performance improvements, William Yaoh for writing documentation, Mike Pilgrem for ImageMagick v7 support, and Xie Ruifeng for LaTeX and text encoding fixes. Furthermore, I'd like to thank Eve, Joe, Rodrigo, Brad, Aron, and Ben for their help and support. Finally, I'd like to thank the GitHub sponsors who are financing server costs and making Reanimate the best it can be.

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll be sure to feature this in the upcoming issue.

**Comment by Lemmih** [comment]
Thanks.
