### ISSUE TITLE
Possible news item

### ISSUE THREAD

**Issue by jwoudenberg** [haskellweekly/haskellweekly#53]
Hi! I built a Generics cheatsheet recently and wondered if it's worth inclusion in the newsletter.

Link: https://generics.jasperwoudenberg.com/

**Comment by tfausak** [comment]
Cool! I'll be sure to feature it in the upcoming issue.

**Comment by tfausak** [comment]
Fixed by ceff87c13881b6c2ab9e10b8ff40faad7942b85b.
