### ISSUE TITLE
gamedev news

### ISSUE THREAD

**Issue by dpwiz** [haskellweekly/haskellweekly#58]
This Ludum Dare game jam got entries two entries (100% growth from the previous one!):
* https://ldjam.com/events/ludum-dare/47/echoes-of-ouroboros (gloss)
* https://ldjam.com/events/ludum-dare/47/orboros (vulkan)

The second one was a test case for a new [vulkan](https://hackage.haskell.org/package/vulkan) wrapper library: https://gitlab.com/dpwiz/vulkan-setup

Also, [gamedev subreddit](https://www.reddit.com/r/haskellgamedev/) is a thing, and now [discord](https://discord.gg/aBBydTH) too. #haskell-game (on Freenode and [matrix](https://app.element.io/#/room/#freenode_#haskell-game:matrix.org)) never went away though.

**Comment by tfausak** [comment]
Thanks for the suggestions! I'll be sure to include these games in the show and tell section.

**Comment by tfausak** [comment]
Fixed by 2ee086ae32963cc5d0d9b2fa2806f06c0cba874d. Thanks again!
