### ISSUE TITLE
Guide to building hardware with Clash on the VELDT

### ISSUE THREAD

**Issue by dopamane** [haskellweekly/haskellweekly#63]
Hello, I wrote a guide to building hardware with Clash on the VELDT. It'd be awesome to have it featured by HaskellWeekly!

[Where Lions Roam: Haskell & Hardware on the VELDT](https://github.com/standardsemiconductor/VELDT-getting-started)

**Comment by tfausak** [comment]
Thanks for the suggestion! I'll be sure to feature this in the upcoming issue of Haskell Weekly.

**Comment by tfausak** [comment]
This was fixed by 8bda21d98486f76057d301f1ebe0a5a7e39a01c4.
