### ISSUE TITLE
Contributing 

### ISSUE THREAD

**Issue by jkeuhlen** [haskellweekly/haskellweekly#7]
Hello! A coworker suggested I ask my recent blog post to be included in Haskell Weekly. 

https://jkeuhlen.com/2019/10/19/Compile-Your-Comments-In-Ghcid.html

I'm not sure what all you need from me, but if you think it would be a good fit please let me know!

**Comment by tfausak** [comment]
Thanks for the suggestion! Fixed by 159a34f6e377def3171b5ac8fc9725b4967b2b5f and published in issue 183.
