### ISSUE TITLE
Haskell Weekly Contribution

### ISSUE THREAD

**Issue by jkeuhlen** [haskellweekly/haskellweekly#70]
Hello! It's been awhile since I wrote anything, but after writing this short article my co-worker suggested I should submit it for consideration. 

https://jkeuhlen.com/2021/02/13/Production-Webservers-and-Concurrent-Requests.html

Thanks in advance, and let me know if you need any other information.

**Comment by tfausak** [comment]
Looks great! If you'd like to open a PR adding that post I'd be happy to merge it. Otherwise I'll be sure to add the post tomorrow along with all the usual stuff.

**Comment by jkeuhlen** [comment]
Thanks! I'll just open a PR directly next time :)
