### ISSUE TITLE
PureScript 0.14 Release

### ISSUE THREAD

**Issue by thomashoneyman** [haskellweekly/haskellweekly#71]
PureScript 0.14 [has officially been released](https://discourse.purescript.org/t/purescript-0-14-released/2148). The Haskell community usually seems interested in PureScript content so I thought it would be a good fit. The new release features polykinds and safe zero-cost coercions, among other improvements.

I'm not sure what the best resource to link to is -- the Discourse post has the most information, but you may want to link just to the release notes themselves if you think that's what the Haskell community would prefer.

**Comment by tfausak** [comment]
Thanks for the suggestion! I've included this in today's issue.
