### ISSUE TITLE
Haskell Developer Wanted for Full Time Job at Concordium

### ISSUE THREAD

**Issue by mariamalia** [haskellweekly/haskellweekly#78]
[Concordium's Tech team](https://concordium.com/) is looking for Haskell developers that can help us fulfill the promises in our roadmap. 

Our Tech team in Denmark works in close cooperation with leading scientists and researchers to implement an open, permissionless blockchain. We will launch our mainnet in Q2 2021. 

The Concordium blockchain is written partly in Rust and partly in Haskell. **As a Haskell developer you will be involved in most aspects of blockchain technology including implementation of a smart contract language, cryptographic protocols, consensus and transaction layers**. Being part of the development team, you will be involved in all parts of the development life-cycle from the initial specification to the final testing.

We are looking for developers with a master’s degree or PhD in computer science or a related area and it is a requirement that you have worked with Haskell for at least 2 years. We expect that you have a genuine interest in blockchain and distributed systems.

We can offer a challenging job in an international environment with highly educated and skilled colleagues and a close collaboration with a number of universities. 

**While the Tech team is placed in Aarhus in Denmark, it will be possible to work remotely from within the same time zone (+/- 1 hour)**. You will be expected to take part in regular meetings at our offices in Aarhus and Zürich.

If you think this sounds interesting, please send your CV and a short cover letter “why me” to jobs@concordium.com

**Comment by tfausak** [comment]
Thanks for the heads up. I'll include a brief mention in this week's issue of Haskell Weekly. If you'd like anything more, please see this page: https://haskellweekly.news/advertising.html
