### ISSUE TITLE
Article on Haskell weekly about using FRP Events/Behaviors for WebAudio

### ISSUE THREAD

**Issue by mikesol** [haskellweekly/haskellweekly#79]
I recently submitted a camera-ready publication to WAC2011 about using PureScript to pilot the WebAudio API. It starts from looking at how to model the current web audio graph as a Behavior and then dives into the implementation of the Behavior using comonads, indexed monads, linear types, existential types and inductive types. The paper can be found [here](https://meeshkan-public-assets.s3-eu-west-1.amazonaws.com/wac2021/final.pdf).

I'd like to submit a version of the article to Haskell weekly in hopes that it encourages Haskellers to make more creative work with the Web Audio API. Please let me know if that is of interest! If so, I can tweak it to fit a good format for Haskell weekly. The advantage of it being an online publication is that it can have musical examples directly in iframes, so the musical examples can ideally be available directly in the body of the article.

**Comment by tfausak** [comment]
Sounds interesting! 

Sorry it took me so long to reply. I'll include a link to your paper in this week's issue of Haskell Weekly. If you publish anything else, let me know! I'd be happy to accept a PR as well.

**Comment by mikesol** [comment]
Thanks for including the link!
