### ISSUE TITLE
Haskell developer, full-time position at Zimpler, Gothenburg, Sweden

### ISSUE THREAD

**Issue by magthe** [haskellweekly/haskellweekly#82]
We are looking for Haskell developers: http://careers.zimpler.com/jobs/1170463-haskell-developer-to-zimpler

Would love to see it included in HWN if possible, just a link is enough, something short, like:

[Haskell developer, Zimpler in Gothenburg, Sweden](http://careers.zimpler.com/jobs/1170463-haskell-developer-to-zimpler)

**Comment by tfausak** [comment]
Thanks for the heads up! I included this in [issue 263](https://haskellweekly.news/issue/263.html). If you'd like to include it in future issues, consider purchasing an ad: https://haskellweekly.news/advertising.html
