### ISSUE TITLE
Haskell developer position opening in Malmö, Sweden

### ISSUE THREAD

**Issue by lorenzo** [haskellweekly/haskellweekly#83]
Hi Taylor, thanks for your great work on the Haskell Weekly newsletter and podcast, I always enjoy it whenever a new edition is out.

Would it be possible to include a new Haskell job opening in the newsletter? We are looking for Haskell developers at Boozt: https://careers.booztgroup.com/jobs/1206300-full-stack-engineer-booztpay

The title could say, for instance:
Haskell developer, at BoozPay Malmö, Sweden.

**Comment by tfausak** [comment]
Thanks for the heads up! I'll be sure to include this in the upcoming issue. If you're interested in more than that, you can buy ad space: https://haskellweekly.news/advertising.html

**Comment by lorenzo** [comment]
@tfausak great idea! I'll discuss this with the recruiting team
