### ISSUE TITLE
Refactoring services

### ISSUE THREAD

**Issue by AriFordsham** [haskellweekly/haskellweekly#89]
Hi Taylor and Cameron,

I really enjoy both the newsletter and podcast every week. The newsletter is the only mailing that I've allowed to come to my Primary tab in Gmail, and it puts a huge smile on my face every time it drops in on Thursday.

Would you be able to include this post of mine?

https://discourse.haskell.org/t/what-can-i-refactor-for-you-today/2820

Unfortunately, I'm not in a position to pay for an ad right now, although that would probably be appropriate, but I'm not asking for it to run for more than one week.

On another topic, I would love to hear a podcast episode on your workflow at IT Pro TV. You keep mentioning it, and making me so curious! Do you use servant or Yesod? What libraries do you use? What dev tools? GHC extensions? What are your coding guidelines? What is your build/CI pipeline? (Apologies if you've done it aand I've missed it!)

Thanks, 

Ari Fordsham

**Comment by tfausak** [comment]
Hi Ari! I'd be happy to feature your post in the upcoming issue of Haskell Weekly. 

We'll definitely consider talking about our workflow on the podcast! It's been challenging to find the time recently, but we're hoping to get back into it soon.

**Comment by tfausak** [comment]
Closed by 4622696f87e0ae653e3b905e740e828afa0c9ddd. Visible here: https://haskellweekly.news/issue/275.html
