### ISSUE TITLE
Broken links via google and duck duck go

### ISSUE THREAD

**Issue by joelmccracken** [haskellweekly/haskellweekly#9]
First off, thank you so much for haskell weekly, both the newsletter and the podcast. I really appreciate both resources.

So, sometimes, when I am looking for a tutorial or something, I will use a search like:

https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Fhaskellweekly.news%2F%20cli

However, all of these links now end in a 404. It seems like this is because the older site used to have archive permalinks at e.g. `issues/123.html`, but this is now redirecting to `episodes/123.html`, but the new url should actually be `issue/123.html`.

I really appreciate this newsletter, thanks again. I hope this would be as easy as changing an nginx redirect or something.

**Comment by tfausak** [comment]
Thanks for reporting this! I can’t believe I messed it up 😬 Should be fixed once the new code deploys in a couple minutes.

**Comment by joelmccracken** [comment]
TY so much @tfausak !

**Comment by joelmccracken** [comment]
Just verified, doing this search above results in clickable links. 🎉

**Comment by joelmccracken** [comment]
I was thinking, if I figured out how to add like a search box to the haskell weekly home page, would you accept a PR for that? someone else might find it handy. Basically it would just be a thing that redirects to duckduckgo with `site:https://haskellweekly.news/newsletter.html <search term>`

**Comment by tfausak** [comment]
Yeah, that would be nice! If you're thinking about doing that, it would be worthwhile to open a new issue for it. 

Also, for what it's worth, Haskell Weekly is actually a web service now (rather than a static site). So it could conceivably support search itself, although I doubt the quality would be as good as DDG or Google.
